spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Retrate123
    url: jdbc:mysql://localhost:3306/patientPortalDB
    username: root
    static-locations: classpath:/static/,classpath:/notebooks/

server:
  port: 9015
  error:
    include-message: always
